import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, CircleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTASection, FAQSection, SectionHeading } from "@/components/site/site-ui";
import { InterfaceVisual, ProcessTimeline, ServicesGrid } from "@/components/site/content";
import { ProjectGrid } from "@/components/site/project-dialog";
import { values } from "@/data/site";

export const Route = createFileRoute("/")({ head:()=>({ meta:[{title:"Veldepu AI — Better Websites. Smarter Automation."},{name:"description",content:"Veldepu AI creates modern websites and practical business automation that helps businesses work smarter."},{property:"og:title",content:"Veldepu AI — Better Websites. Smarter Automation."},{property:"og:description",content:"Modern websites and practical business automation built for growth."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: Home });
function Home(){ const problems=["Outdated websites","Poor online presence","Manual repetitive work","Missed customer inquiries","Slow business processes","Disconnected tools"]; return <>
<section className="relative overflow-hidden bg-foreground text-background"><div className="hero-grid absolute inset-0 opacity-10"/><div className="site-container relative grid min-h-[calc(100svh-4.5rem)] items-center gap-12 py-16 lg:grid-cols-[1.08fr_0.92fr] lg:py-20"><div className="animate-rise"><p className="mb-5 text-xs font-semibold uppercase text-brand-soft">Websites · Redesign · Automation</p><h1 className="font-display text-5xl font-semibold leading-[0.98] sm:text-7xl lg:text-8xl">Build better.<br/><span className="text-brand-soft">Automate smarter.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-background/70">Veldepu AI creates modern websites and practical business automation designed to help businesses work smarter.</p><div className="mt-9 flex flex-wrap gap-3"><Button asChild size="lg" variant="light"><Link to="/contact">Start a Project<ArrowRight/></Link></Button><Button asChild size="lg" variant="dark-outline"><Link to="/services">Explore Services<ArrowDown/></Link></Button></div></div><InterfaceVisual/></div></section>
<section className="border-b border-border bg-card"><div className="site-container grid sm:grid-cols-2 lg:grid-cols-4">{values.map(({title,text,icon:Icon})=><article key={title} className="border-b border-border py-7 sm:px-6 sm:[&:nth-child(odd)]:border-r lg:border-b-0 lg:border-r lg:first:pl-0 lg:last:border-r-0"><Icon className="size-5 text-primary"/><h2 className="mt-4 font-display text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{text}</p></article>)}</div></section>
<section className="section-space"><div className="site-container"><SectionHeading eyebrow="The challenge" title="Good businesses lose momentum to avoidable friction." description="When the website and day-to-day systems fall behind, customers feel it—and teams spend time compensating."/><div className="mt-10 grid gap-px overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{problems.map((problem)=><div className="flex items-center gap-3 bg-card p-5" key={problem}><CircleAlert className="size-5 text-primary"/><span className="font-medium">{problem}</span></div>)}</div><Button asChild className="mt-8" variant="outline"><Link to="/services">See How We Help<ArrowRight/></Link></Button></div></section>
<section className="section-space border-y border-border bg-surface-soft"><div className="site-container"><SectionHeading eyebrow="What we do" title="Three focused services. One clear objective." description="Create a stronger digital experience and make the work behind it more efficient."/><div className="mt-12"><ServicesGrid/></div></div></section>
<section className="section-space"><div className="site-container"><SectionHeading eyebrow="Our process" title="A clear route from idea to launch." description="Simple stages keep decisions focused and progress visible."/><div className="mt-10"><ProcessTimeline compact/></div><Button asChild variant="outline" className="mt-8"><Link to="/process">View Our Process<ArrowRight/></Link></Button></div></section>
<section className="section-space border-t border-border bg-surface-soft"><div className="site-container"><SectionHeading eyebrow="Selected concepts" title="Thinking made visible." description="Exploratory concept work that demonstrates our approach. These are not presented as client projects."/><div className="mt-10"><ProjectGrid limit={3}/></div></div></section><FAQSection/><CTASection/>
</>}
