import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { projects } from "@/data/site";

export function ProjectGrid({ limit }: { limit?: number }) {
  const visible = typeof limit === "number" ? projects.slice(0, limit) : projects;
  return <div className="grid gap-5 lg:grid-cols-3">{visible.map((project, index) => <Dialog key={project.name}><article className="flex min-h-full flex-col overflow-hidden rounded-lg border border-border bg-card shadow-sm"><div className="relative aspect-[16/10] overflow-hidden bg-foreground p-6"><div className="absolute inset-0 hero-grid opacity-20"/><div className="relative flex h-full flex-col justify-between rounded-md border border-background/20 bg-background/5 p-4"><span className="w-fit rounded-full bg-background px-3 py-1 text-xs font-semibold text-foreground">{project.label}</span><span className="font-display text-5xl font-semibold text-background/30">0{index + 1}</span></div></div><div className="flex flex-1 flex-col p-6"><p className="text-xs font-semibold uppercase text-primary">{project.category}</p><h3 className="mt-2 font-display text-2xl font-semibold">{project.name}</h3><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{project.description}</p><DialogTrigger asChild><Button variant="outline" className="mt-6 w-full">View Project<ArrowUpRight /></Button></DialogTrigger></div></article><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto rounded-lg p-7 sm:p-9"><DialogHeader><p className="text-xs font-semibold uppercase text-primary">{project.label} · {project.category}</p><DialogTitle className="font-display text-3xl">{project.name}</DialogTitle><DialogDescription className="pt-2 leading-7">{project.description}</DialogDescription></DialogHeader><div className="my-3 grid gap-6 sm:grid-cols-2"><div><h4 className="font-display font-semibold">The challenge</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{project.challenge}</p></div><div><h4 className="font-display font-semibold">Concept outcome</h4><p className="mt-2 text-sm leading-6 text-muted-foreground">{project.outcome}</p></div></div><div className="flex flex-wrap gap-2">{project.technologies.map((tech)=><span key={tech} className="rounded-full bg-accent px-3 py-1 text-xs font-medium text-accent-foreground">{tech}</span>)}</div><DialogFooter className="mt-3"><DialogClose asChild><Button variant="outline"><ArrowLeft />Back to Work</Button></DialogClose></DialogFooter></DialogContent></Dialog>)}</div>;
}
